server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/duzz_blog?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

